### ISSUE TITLE
Remove erfgeo branch

### ISSUE THREAD

**Issue by bertspaan** [erfgoed-en-locatie/histograph-viewer#17]
Remove erfgeo branch from repo.

**Comment by Ivokato** [comment]
seems to be done already

**Comment by bertspaan** [comment]
![image](https://cloud.githubusercontent.com/assets/1194896/8208617/d7072a2a-1508-11e5-9f82-9fddd6a21e83.png)

**Comment by Ivokato** [comment]
![screen shot 2015-06-17 at 16 10 42](https://cloud.githubusercontent.com/assets/6028809/8209049/2752bbe6-150b-11e5-8f2e-d79dcf07036a.png)

**Comment by bertspaan** [comment]
:dancers:
