### ISSUE TITLE
Do only q=<query> queries

### ISSUE THREAD

**Issue by bertspaan** [erfgoed-en-locatie/histograph-viewer#18]
On https://github.com/histograph/viewer/blob/develop/src/app.js#L117, the Viewer converts creates `?name=<query>`, `?hgid=<query>` or `?uri=<query>` queries to the Histograph API, depending on the contents of the query string. This is not needed anymore (since https://github.com/histograph/api/commit/9f54dd3fb601ba1d84382b42f79e57ad9e679bd6, the API accepts `?q=<query>` queries, where `<query>` can contain URIs, `hgid`s, or names). Also, the `q` paramaters accepts queries like `q=amsterdam,drenthe` and converts those to `q=amsterdam&hg:liesIn=drenthe`.

**Comment by Ivokato** [comment]
fixed, now puts whole query in q=<query> param
