### ISSUE TITLE
Set right links to thesaurus 

### ISSUE THREAD

**Issue by mmmenno** [erfgoed-en-locatie/histograph-viewer#21]
In the Old Api Days, links were build like [http://thesaurus.erfgeo.nl/hgconcept/tgn-term/1001179635](http://thesaurus.erfgeo.nl/hgconcept/tgn-term/1001179635) and [http://thesaurus.erfgeo.nl/pit/ilvb/1449](http://thesaurus.erfgeo.nl/pit/ilvb/1449). 

In the New Api Era, links should be formed like [http://thesaurus.erfgeo.nl/hgconcept/?id=http://vocab.getty.edu/tgn/term/1001179635](http://thesaurus.erfgeo.nl/hgconcept/?id=http://vocab.getty.edu/tgn/term/1001179635) and [http://thesaurus.erfgeo.nl/pit/?id=ilvb/1449](http://thesaurus.erfgeo.nl/pit/?id=ilvb/1449)

**Comment by wires** [comment]
staat op http://histograph.io/viewer/#search=naarden (`simple` viewer)
