### ISSUE TITLE
Viewer doesn't recognize parameters from url, as in #search=*&type=hg:Departement

### ISSUE THREAD

**Issue by mmmenno** [erfgoed-en-locatie/histograph-viewer#22]
When you search for `*&type=hg:Departement` in the searchbox, the departements pop up on the map and the url is set to [http://histograph.io/viewer/#search=*&type=hg:Departement](http://histograph.io/viewer/#search=*&type=hg:Departement).

However, when you reload or try to follow the link above, the `&type=hg:Departement` part mysteriously disappears and the viewer tries to serve all pits in the system.

**Comment by wires** [comment]
ja, dit viel my ook al op

**Comment by mmmenno** [comment]
Ben alle artikeltjes aan het nalopen en kwam een link naar kaart met departementen tegen. Heb ik nu zo maar opgelost:

> Je kan alle departementen tevoorschijn halen door naar de viewer te gaan en *&type=hg:Departement in het zoekboxje te typen.
