### ISSUE TITLE
Invalid serve hints on npm start

### ISSUE THREAD

**Issue by reinvantveer** [erfgoed-en-locatie/histograph-viewer#25]
reinv@lingui:~/data/Github/histograph/histograph-viewer$ npm start

> histograph-viewer@0.5.0 start /var/data/Github/histograph/histograph-viewer
> NODE_ENV=development node viewer-config.js > config.json && watchify -d -t reactify src/index.js -o dist/bundle.js & serve

Please specify location of your user configuration in environment variable `HISTOGRAPH_CONFIG`, or use the `--config` command line option
serving /var/data/Github/histograph/histograph-viewer on port 3000
^C

reinv@lingui:~/data/Github/histograph/histograph-viewer$ npm start --config $PWD/../config/config.yml

> histograph-viewer@0.5.0 start /var/data/Github/histograph/histograph-viewer
> NODE_ENV=development node viewer-config.js > config.json && watchify -d -t reactify src/index.js -o dist/bundle.js & serve "/home/reinv/data/Github/histograph/histograph-viewer/../config/config.yml"

Please specify location of your user configuration in environment variable `HISTOGRAPH_CONFIG`, or use the `--config` command line option
serving /home/reinv/data/Github/histograph/config/config.yml on port 3000
Error: ENOTDIR: not a directory, stat '/home/reinv/data/Github/histograph/config/config.yml/'
    at Error (native)

**Comment by bertspaan** [comment]
Can you reformat your issue? It's hard to read + understand.

**Comment by reinvantveer** [comment]
Histograph-viewer seems to append an extra '/' when used with the --config CLI option.

To reproduce:
1. use `npm start` instruction from docs

```
reinv@lingui:~/data/Github/histograph/histograph-viewer$ npm start

> histograph-viewer@0.5.0 start /var/data/Github/histograph/histograph-viewer
> NODE_ENV=development node viewer-config.js > config.json && watchify -d -t reactify src/index.js -o dist/bundle.js & serve

Please specify location of your user configuration in environment variable `HISTOGRAPH_CONFIG`, or use the `--config` command line option
serving /var/data/Github/histograph/histograph-viewer on port 3000
```

Pressed ^C
1. used `Please specify location of your user configuration in environment variable `HISTOGRAPH_CONFIG`, or use the `--config` command line option` option as `--config` parameter

```
reinv@lingui:~/data/Github/histograph/histograph-viewer$ npm start --config $PWD/../config/config.yml

> histograph-viewer@0.5.0 start /var/data/Github/histograph/histograph-viewer
> NODE_ENV=development node viewer-config.js > config.json && watchify -d -t reactify src/index.js -o dist/bundle.js & serve "/home/reinv/data/Github/histograph/histograph-viewer/../config/config.yml"

Please specify location of your user configuration in environment variable `HISTOGRAPH_CONFIG`, or use the `--config` command line option
serving /home/reinv/data/Github/histograph/config/config.yml on port 3000
Error: ENOTDIR: not a directory, stat '/home/reinv/data/Github/histograph/config/config.yml/'
    at Error (native)
```

**Comment by reinvantveer** [comment]
Sorry was a bit quick I suppose with the previous comment :)

**Comment by bertspaan** [comment]
Oh, yeah... You cannot pass the `--config` option with `npm start`... 

"Please specify location of your user configuration..." is output from `viewer-config.js`, you should add the  `--config` option to the `scripts` section in `package.json`, or just set the environment variable!

**Comment by bertspaan** [comment]
This is confusing, I agree... We should update README.

**Comment by sbocconi** [comment]
Updated readme
